[tox]
minversion = 4.0
envlist = py39, py310, py311, py312, py313, format, lint, docs
isolated_build = true

[testenv]
package = wheel
passenv = *
deps =
    pytest
    pytest-cov
commands =
    pytest tests --cov --cov-config=pyproject.toml --cov-report=xml {posargs}

[testenv:py]
basepython = python

[testenv:format]
skip_install = true
deps =
    isort
    black
    ruff
commands =
    isort tests examples python
    black tests examples python
    ruff format tests examples python

[testenv:lint]
skip_install = true
deps =
    black
    flake8
    mypy
    ruff
commands =
    black --check tests examples python
    flake8 tests examples python
    mypy tests examples --ignore-missing-imports
    ruff check tests examples python

[testenv:docs]
skip_install = true
deps =
    mkdocs
    mkdocs-include-markdown-plugin
    mkdocs-material
    mkdocstrings
    mkdocs-autorefs
commands =
    mkdocs build
