"""High-level pymp4v2 API.

Hand-written to match the pybind11 bindings. Sample indices on Track are
0-based; ``pymp4v2.raw.MP4ReadSample`` is 1-based.
"""

from __future__ import annotations

from types import TracebackType
from typing import Iterator, Optional

from . import raw
from .raw import MP4Sample as Sample

__version__: str
__all__: list[str]

class MP4Error(RuntimeError):
    """Raised when a C call returns false / MP4_INVALID_* or a closed handle is used."""

class Track:
    """One track of an MP4File. Sample indices are 0-based."""

    @property
    def id(self) -> int: ...
    @property
    def type(self) -> str: ...
    @property
    def duration(self) -> int: ...
    @property
    def timescale(self) -> int: ...
    @property
    def sample_count(self) -> int: ...
    @property
    def language(self) -> Optional[str]: ...
    @property
    def name(self) -> Optional[str]: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def bitrate(self) -> int: ...
    @property
    def frame_rate(self) -> float: ...
    @property
    def audio_channels(self) -> Optional[int]: ...
    def read_sample(self, index: int) -> Sample: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Sample: ...
    def __iter__(self) -> Iterator[Sample]: ...

class Tracks:
    """Sequence of Track objects on an MP4File."""

    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Track: ...
    def __iter__(self) -> Iterator[Track]: ...

class Tags:
    """iTMF tags on an MP4File. Fetch on first access; store() on context exit if dirty."""

    def fetch(self) -> None: ...
    def store(self) -> None: ...
    def add_artwork(self, data: bytes, type: int = ...) -> None: ...
    def remove_artwork(self, index: int) -> None: ...
    @property
    def artwork(self) -> list[bytes]: ...
    @property
    def artwork_count(self) -> int: ...
    def __enter__(self) -> Tags: ...
    def __exit__(
        self,
        exc_type: Optional[type[BaseException]],
        exc: Optional[BaseException],
        tb: Optional[TracebackType],
    ) -> bool: ...
    @property
    def name(self) -> Optional[str]: ...
    @name.setter
    def name(self, value: Optional[str]) -> None: ...
    @property
    def artist(self) -> Optional[str]: ...
    @artist.setter
    def artist(self, value: Optional[str]) -> None: ...
    @property
    def album_artist(self) -> Optional[str]: ...
    @album_artist.setter
    def album_artist(self, value: Optional[str]) -> None: ...
    @property
    def album(self) -> Optional[str]: ...
    @album.setter
    def album(self, value: Optional[str]) -> None: ...
    @property
    def grouping(self) -> Optional[str]: ...
    @grouping.setter
    def grouping(self, value: Optional[str]) -> None: ...
    @property
    def composer(self) -> Optional[str]: ...
    @composer.setter
    def composer(self, value: Optional[str]) -> None: ...
    @property
    def comments(self) -> Optional[str]: ...
    @comments.setter
    def comments(self, value: Optional[str]) -> None: ...
    @property
    def genre(self) -> Optional[str]: ...
    @genre.setter
    def genre(self, value: Optional[str]) -> None: ...
    @property
    def release_date(self) -> Optional[str]: ...
    @release_date.setter
    def release_date(self, value: Optional[str]) -> None: ...
    @property
    def description(self) -> Optional[str]: ...
    @description.setter
    def description(self, value: Optional[str]) -> None: ...
    @property
    def long_description(self) -> Optional[str]: ...
    @long_description.setter
    def long_description(self, value: Optional[str]) -> None: ...
    @property
    def lyrics(self) -> Optional[str]: ...
    @lyrics.setter
    def lyrics(self, value: Optional[str]) -> None: ...
    @property
    def copyright(self) -> Optional[str]: ...
    @copyright.setter
    def copyright(self, value: Optional[str]) -> None: ...
    @property
    def encoding_tool(self) -> Optional[str]: ...
    @encoding_tool.setter
    def encoding_tool(self, value: Optional[str]) -> None: ...
    @property
    def encoded_by(self) -> Optional[str]: ...
    @encoded_by.setter
    def encoded_by(self, value: Optional[str]) -> None: ...
    @property
    def tv_show(self) -> Optional[str]: ...
    @tv_show.setter
    def tv_show(self, value: Optional[str]) -> None: ...
    @property
    def tv_network(self) -> Optional[str]: ...
    @tv_network.setter
    def tv_network(self, value: Optional[str]) -> None: ...
    @property
    def tv_episode_id(self) -> Optional[str]: ...
    @tv_episode_id.setter
    def tv_episode_id(self, value: Optional[str]) -> None: ...
    @property
    def sort_name(self) -> Optional[str]: ...
    @sort_name.setter
    def sort_name(self, value: Optional[str]) -> None: ...
    @property
    def sort_artist(self) -> Optional[str]: ...
    @sort_artist.setter
    def sort_artist(self, value: Optional[str]) -> None: ...
    @property
    def sort_album_artist(self) -> Optional[str]: ...
    @sort_album_artist.setter
    def sort_album_artist(self, value: Optional[str]) -> None: ...
    @property
    def sort_album(self) -> Optional[str]: ...
    @sort_album.setter
    def sort_album(self, value: Optional[str]) -> None: ...
    @property
    def sort_composer(self) -> Optional[str]: ...
    @sort_composer.setter
    def sort_composer(self, value: Optional[str]) -> None: ...
    @property
    def sort_tv_show(self) -> Optional[str]: ...
    @sort_tv_show.setter
    def sort_tv_show(self, value: Optional[str]) -> None: ...
    @property
    def purchase_date(self) -> Optional[str]: ...
    @purchase_date.setter
    def purchase_date(self, value: Optional[str]) -> None: ...
    @property
    def keywords(self) -> Optional[str]: ...
    @keywords.setter
    def keywords(self, value: Optional[str]) -> None: ...
    @property
    def category(self) -> Optional[str]: ...
    @category.setter
    def category(self, value: Optional[str]) -> None: ...
    @property
    def itunes_account(self) -> Optional[str]: ...
    @itunes_account.setter
    def itunes_account(self, value: Optional[str]) -> None: ...
    @property
    def xid(self) -> Optional[str]: ...
    @xid.setter
    def xid(self, value: Optional[str]) -> None: ...
    @property
    def genre_type(self) -> Optional[int]: ...
    @genre_type.setter
    def genre_type(self, value: Optional[int]) -> None: ...
    @property
    def tempo(self) -> Optional[int]: ...
    @tempo.setter
    def tempo(self, value: Optional[int]) -> None: ...
    @property
    def compilation(self) -> Optional[int]: ...
    @compilation.setter
    def compilation(self, value: Optional[int]) -> None: ...
    @property
    def tv_season(self) -> Optional[int]: ...
    @tv_season.setter
    def tv_season(self, value: Optional[int]) -> None: ...
    @property
    def tv_episode(self) -> Optional[int]: ...
    @tv_episode.setter
    def tv_episode(self, value: Optional[int]) -> None: ...
    @property
    def podcast(self) -> Optional[int]: ...
    @podcast.setter
    def podcast(self, value: Optional[int]) -> None: ...
    @property
    def hd_video(self) -> Optional[int]: ...
    @hd_video.setter
    def hd_video(self, value: Optional[int]) -> None: ...
    @property
    def media_type(self) -> Optional[int]: ...
    @media_type.setter
    def media_type(self, value: Optional[int]) -> None: ...
    @property
    def content_rating(self) -> Optional[int]: ...
    @content_rating.setter
    def content_rating(self, value: Optional[int]) -> None: ...
    @property
    def gapless(self) -> Optional[int]: ...
    @gapless.setter
    def gapless(self, value: Optional[int]) -> None: ...
    @property
    def itunes_account_type(self) -> Optional[int]: ...
    @itunes_account_type.setter
    def itunes_account_type(self, value: Optional[int]) -> None: ...
    @property
    def itunes_country(self) -> Optional[int]: ...
    @itunes_country.setter
    def itunes_country(self, value: Optional[int]) -> None: ...
    @property
    def content_id(self) -> Optional[int]: ...
    @content_id.setter
    def content_id(self, value: Optional[int]) -> None: ...
    @property
    def artist_id(self) -> Optional[int]: ...
    @artist_id.setter
    def artist_id(self, value: Optional[int]) -> None: ...
    @property
    def playlist_id(self) -> Optional[int]: ...
    @playlist_id.setter
    def playlist_id(self, value: Optional[int]) -> None: ...
    @property
    def genre_id(self) -> Optional[int]: ...
    @genre_id.setter
    def genre_id(self, value: Optional[int]) -> None: ...
    @property
    def composer_id(self) -> Optional[int]: ...
    @composer_id.setter
    def composer_id(self, value: Optional[int]) -> None: ...
    @property
    def track(self) -> Optional[raw.MP4TagTrack]: ...
    @track.setter
    def track(self, value: Optional[raw.MP4TagTrack]) -> None: ...
    @property
    def disk(self) -> Optional[raw.MP4TagDisk]: ...
    @disk.setter
    def disk(self, value: Optional[raw.MP4TagDisk]) -> None: ...

class MP4File:
    """High-level owner of an MP4FileHandle."""

    def __init__(self, filename: str, mode: str = "r") -> None: ...
    def close(self) -> None: ...
    def get_track_count(self) -> int: ...
    def save(self) -> None: ...
    def is_open(self) -> bool: ...
    def get_info(self) -> str: ...
    @property
    def info(self) -> str: ...
    @property
    def filename(self) -> str: ...
    @property
    def mode(self) -> str: ...
    @property
    def duration(self) -> int: ...
    @property
    def timescale(self) -> int: ...
    @property
    def tracks(self) -> Tracks: ...
    @property
    def tags(self) -> Tags: ...
    def optimize(self, new_filename: Optional[str] = None) -> None: ...
    def __enter__(self) -> MP4File: ...
    def __exit__(
        self,
        exc_type: Optional[type[BaseException]],
        exc: Optional[BaseException],
        tb: Optional[TracebackType],
    ) -> bool: ...
