"""1:1 stubs for the bound subset of the MP4v2 C API.

C names are kept. Sample payloads and artwork are ``bytes``. C failures
(``false`` / ``MP4_INVALID_*``) raise ``MP4Error``, except predicates such as
``MP4HaveAtom``.
"""

from __future__ import annotations

import enum
from types import TracebackType
from typing import Iterator, Optional, Sequence, Union

from . import MP4Error as MP4Error

# Type aliases: ints at the C++ boundary and at runtime (not typing.NewType).
MP4TrackId = int
MP4SampleId = int
MP4Timestamp = int
MP4Duration = int
MP4EditId = int

MP4_INVALID_TRACK_ID: int
MP4_INVALID_SAMPLE_ID: int
MP4_INVALID_TIMESTAMP: int
MP4_INVALID_DURATION: int
MP4_INVALID_EDIT_ID: int
MP4_CLOSE_DO_NOT_COMPUTE_BITRATE: int
MP4_CREATE_64BIT_DATA: int
MP4_CREATE_64BIT_TIME: int
MP4_OD_TRACK_TYPE: str
MP4_SCENE_TRACK_TYPE: str
MP4_AUDIO_TRACK_TYPE: str
MP4_VIDEO_TRACK_TYPE: str
MP4_HINT_TRACK_TYPE: str
MP4_CNTL_TRACK_TYPE: str
MP4_TEXT_TRACK_TYPE: str
MP4_SUBTITLE_TRACK_TYPE: str
MP4_SUBPIC_TRACK_TYPE: str
MP4_CLOCK_TRACK_TYPE: str
MP4_MPEG7_TRACK_TYPE: str
MP4_OCI_TRACK_TYPE: str
MP4_IPMP_TRACK_TYPE: str
MP4_MPEGJ_TRACK_TYPE: str
MP4_MPEG4_AUDIO_TYPE: int
MP4_MPEG4_VIDEO_TYPE: int
MP4V2_CHAPTER_TITLE_MAX: int

class MP4LogLevel(enum.IntEnum):
    MP4_LOG_NONE = ...
    MP4_LOG_ERROR = ...
    MP4_LOG_WARNING = ...
    MP4_LOG_INFO = ...
    MP4_LOG_VERBOSE1 = ...
    MP4_LOG_VERBOSE2 = ...
    MP4_LOG_VERBOSE3 = ...
    MP4_LOG_VERBOSE4 = ...

MP4_LOG_NONE: MP4LogLevel
MP4_LOG_ERROR: MP4LogLevel
MP4_LOG_WARNING: MP4LogLevel
MP4_LOG_INFO: MP4LogLevel
MP4_LOG_VERBOSE1: MP4LogLevel
MP4_LOG_VERBOSE2: MP4LogLevel
MP4_LOG_VERBOSE3: MP4LogLevel
MP4_LOG_VERBOSE4: MP4LogLevel

class MP4TagArtworkType_e(enum.IntEnum):
    MP4_ART_UNDEFINED = ...
    MP4_ART_BMP = ...
    MP4_ART_GIF = ...
    MP4_ART_JPEG = ...
    MP4_ART_PNG = ...

MP4_ART_UNDEFINED: MP4TagArtworkType_e
MP4_ART_BMP: MP4TagArtworkType_e
MP4_ART_GIF: MP4TagArtworkType_e
MP4_ART_JPEG: MP4TagArtworkType_e
MP4_ART_PNG: MP4TagArtworkType_e

class MP4ChapterType(enum.IntEnum):
    MP4ChapterTypeNone = ...
    MP4ChapterTypeAny = ...
    MP4ChapterTypeQt = ...
    MP4ChapterTypeNero = ...

MP4ChapterTypeNone: MP4ChapterType
MP4ChapterTypeAny: MP4ChapterType
MP4ChapterTypeQt: MP4ChapterType
MP4ChapterTypeNero: MP4ChapterType

class MP4FileHandle:
    def __init__(self) -> None: ...
    def is_valid(self) -> bool: ...
    close_flags: int
    def close(self, flags: Optional[int] = None) -> None: ...
    def __enter__(self) -> MP4FileHandle: ...
    def __exit__(
        self,
        exc_type: Optional[type[BaseException]],
        exc: Optional[BaseException],
        tb: Optional[TracebackType],
    ) -> bool: ...

class MP4Sample:
    """One sample from MP4ReadSample: data (bytes) plus timing fields."""

    @property
    def data(self) -> bytes: ...
    startTime: int
    duration: int
    renderingOffset: int
    isSyncSample: bool
    def __iter__(self) -> Iterator[Union[bytes, int, bool]]: ...

class MP4TagArtwork:
    """Artwork item: data is a copy as bytes, type is MP4TagArtworkType."""

    @property
    def data(self) -> bytes: ...
    @property
    def size(self) -> int: ...
    type: MP4TagArtworkType_e

class MP4TagTrack:
    def __init__(self, index: int = ..., total: int = ...) -> None: ...
    index: int
    total: int

class MP4TagDisk:
    def __init__(self, index: int = ..., total: int = ...) -> None: ...
    index: int
    total: int

class MP4Tags:
    """iTMF tags snapshot. Allocate with MP4TagsAlloc(); free with MP4TagsFree()."""

    def __init__(self) -> None: ...
    def is_valid(self) -> bool: ...
    def __enter__(self) -> MP4Tags: ...
    def __exit__(
        self,
        exc_type: Optional[type[BaseException]],
        exc: Optional[BaseException],
        tb: Optional[TracebackType],
    ) -> bool: ...
    @property
    def artwork(self) -> list[MP4TagArtwork]: ...
    @property
    def artworkCount(self) -> int: ...
    @property
    def track(self) -> Optional[MP4TagTrack]: ...
    @property
    def disk(self) -> Optional[MP4TagDisk]: ...
    @property
    def tempo(self) -> Optional[int]: ...
    @property
    def name(self) -> Optional[str]: ...
    @property
    def artist(self) -> Optional[str]: ...
    @property
    def albumArtist(self) -> Optional[str]: ...
    @property
    def album(self) -> Optional[str]: ...
    @property
    def grouping(self) -> Optional[str]: ...
    @property
    def composer(self) -> Optional[str]: ...
    @property
    def comments(self) -> Optional[str]: ...
    @property
    def genre(self) -> Optional[str]: ...
    @property
    def releaseDate(self) -> Optional[str]: ...
    @property
    def tvShow(self) -> Optional[str]: ...
    @property
    def tvNetwork(self) -> Optional[str]: ...
    @property
    def tvEpisodeID(self) -> Optional[str]: ...
    @property
    def description(self) -> Optional[str]: ...
    @property
    def longDescription(self) -> Optional[str]: ...
    @property
    def lyrics(self) -> Optional[str]: ...
    @property
    def sortName(self) -> Optional[str]: ...
    @property
    def sortArtist(self) -> Optional[str]: ...
    @property
    def sortAlbumArtist(self) -> Optional[str]: ...
    @property
    def sortAlbum(self) -> Optional[str]: ...
    @property
    def sortComposer(self) -> Optional[str]: ...
    @property
    def sortTVShow(self) -> Optional[str]: ...
    @property
    def copyright(self) -> Optional[str]: ...
    @property
    def encodingTool(self) -> Optional[str]: ...
    @property
    def encodedBy(self) -> Optional[str]: ...
    @property
    def purchaseDate(self) -> Optional[str]: ...
    @property
    def keywords(self) -> Optional[str]: ...
    @property
    def category(self) -> Optional[str]: ...
    @property
    def iTunesAccount(self) -> Optional[str]: ...
    @property
    def xid(self) -> Optional[str]: ...
    @property
    def genreType(self) -> Optional[int]: ...
    @property
    def compilation(self) -> Optional[int]: ...
    @property
    def tvSeason(self) -> Optional[int]: ...
    @property
    def tvEpisode(self) -> Optional[int]: ...
    @property
    def podcast(self) -> Optional[int]: ...
    @property
    def hdVideo(self) -> Optional[int]: ...
    @property
    def mediaType(self) -> Optional[int]: ...
    @property
    def contentRating(self) -> Optional[int]: ...
    @property
    def gapless(self) -> Optional[int]: ...
    @property
    def iTunesAccountType(self) -> Optional[int]: ...
    @property
    def iTunesCountry(self) -> Optional[int]: ...
    @property
    def contentID(self) -> Optional[int]: ...
    @property
    def artistID(self) -> Optional[int]: ...
    @property
    def playlistID(self) -> Optional[int]: ...
    @property
    def genreID(self) -> Optional[int]: ...
    @property
    def composerID(self) -> Optional[int]: ...

class MP4Chapter:
    def __init__(self, duration: int = ..., title: str = "") -> None: ...
    duration: int
    title: str

class MP4ChapterList:
    type: MP4ChapterType
    chapters: list[MP4Chapter]
    def __iter__(self) -> Iterator[object]: ...
    def __len__(self) -> int: ...

def MP4Read(fileName: str) -> MP4FileHandle: ...
def MP4Create(fileName: str, flags: int = 0) -> MP4FileHandle: ...
def MP4CreateEx(
    fileName: str,
    flags: int = 0,
    add_ftyp: int = 1,
    add_iods: int = 1,
    majorBrand: Optional[str] = None,
    minorVersion: int = 0,
    compatibleBrands: Sequence[str] = (),
) -> MP4FileHandle: ...
def MP4Modify(fileName: str, flags: int = 0) -> MP4FileHandle: ...
def MP4Close(hFile: MP4FileHandle, flags: int = 0) -> None: ...
def MP4Dump(hFile: MP4FileHandle, dumpImplicits: bool = False) -> bool: ...
def MP4GetFilename(hFile: MP4FileHandle) -> str: ...
def MP4Info(hFile: MP4FileHandle, trackId: int = ...) -> Optional[str]: ...
def MP4FileInfo(fileName: str, trackId: int = ...) -> Optional[str]: ...
def MP4Optimize(fileName: str, newFileName: Optional[str] = None) -> bool: ...
def MP4LogSetLevel(verbosity: MP4LogLevel) -> None: ...
def MP4GetNumberOfTracks(
    hFile: MP4FileHandle, type: Optional[str] = None, subType: int = 0
) -> int: ...
def MP4FindTrackId(
    hFile: MP4FileHandle, index: int, type: Optional[str] = None, subType: int = 0
) -> int: ...
def MP4GetTrackType(hFile: MP4FileHandle, trackId: int) -> str: ...
def MP4DeleteTrack(hFile: MP4FileHandle, trackId: int) -> None: ...
def MP4AddAudioTrack(
    hFile: MP4FileHandle,
    timeScale: int,
    sampleDuration: int,
    audioType: int = ...,
) -> int: ...
def MP4AddVideoTrack(
    hFile: MP4FileHandle,
    timeScale: int,
    sampleDuration: int,
    width: int,
    height: int,
    videoType: int = ...,
) -> int: ...
def MP4HaveAtom(hFile: MP4FileHandle, atomName: str) -> bool: ...
def MP4GetDuration(hFile: MP4FileHandle) -> int: ...
def MP4GetTimeScale(hFile: MP4FileHandle) -> int: ...
def MP4SetTimeScale(hFile: MP4FileHandle, value: int) -> None: ...
def MP4GetTrackDuration(hFile: MP4FileHandle, trackId: int) -> int: ...
def MP4GetTrackTimeScale(hFile: MP4FileHandle, trackId: int) -> int: ...
def MP4SetTrackTimeScale(hFile: MP4FileHandle, trackId: int, value: int) -> None: ...
def MP4GetTrackVideoWidth(hFile: MP4FileHandle, trackId: int) -> int: ...
def MP4GetTrackVideoHeight(hFile: MP4FileHandle, trackId: int) -> int: ...
def MP4GetTrackLanguage(hFile: MP4FileHandle, trackId: int) -> str: ...
def MP4SetTrackLanguage(hFile: MP4FileHandle, trackId: int, code: str) -> None: ...
def MP4GetTrackName(hFile: MP4FileHandle, trackId: int) -> str: ...
def MP4SetTrackName(hFile: MP4FileHandle, trackId: int, name: str) -> None: ...
def MP4ChangeMovieTimeScale(hFile: MP4FileHandle, value: int) -> None: ...
def MP4GetIntegerProperty(hFile: MP4FileHandle, propName: str) -> int: ...
def MP4GetFloatProperty(hFile: MP4FileHandle, propName: str) -> float: ...
def MP4GetStringProperty(hFile: MP4FileHandle, propName: str) -> str: ...
def MP4GetBytesProperty(hFile: MP4FileHandle, propName: str) -> bytes: ...
def MP4SetIntegerProperty(hFile: MP4FileHandle, propName: str, value: int) -> None: ...
def MP4SetFloatProperty(hFile: MP4FileHandle, propName: str, value: float) -> None: ...
def MP4SetStringProperty(hFile: MP4FileHandle, propName: str, value: str) -> None: ...
def MP4SetBytesProperty(hFile: MP4FileHandle, propName: str, pValue: bytes) -> None: ...
def MP4HaveTrackAtom(hFile: MP4FileHandle, trackId: int, atomName: str) -> bool: ...
def MP4GetTrackMediaDataName(hFile: MP4FileHandle, trackId: int) -> str: ...
def MP4GetTrackFixedSampleDuration(hFile: MP4FileHandle, trackId: int) -> int: ...
def MP4GetTrackBitRate(hFile: MP4FileHandle, trackId: int) -> int: ...
def MP4GetTrackVideoFrameRate(hFile: MP4FileHandle, trackId: int) -> float: ...
def MP4GetTrackAudioChannels(hFile: MP4FileHandle, trackId: int) -> int: ...
def MP4GetTrackESConfiguration(hFile: MP4FileHandle, trackId: int) -> bytes: ...
def MP4SetTrackESConfiguration(
    hFile: MP4FileHandle, trackId: int, pConfig: bytes
) -> None: ...
def MP4GetTrackIntegerProperty(
    hFile: MP4FileHandle, trackId: int, propName: str
) -> int: ...
def MP4GetTrackFloatProperty(
    hFile: MP4FileHandle, trackId: int, propName: str
) -> float: ...
def MP4GetTrackStringProperty(
    hFile: MP4FileHandle, trackId: int, propName: str
) -> str: ...
def MP4GetTrackBytesProperty(
    hFile: MP4FileHandle, trackId: int, propName: str
) -> bytes: ...
def MP4SetTrackIntegerProperty(
    hFile: MP4FileHandle, trackId: int, propName: str, value: int
) -> None: ...
def MP4SetTrackFloatProperty(
    hFile: MP4FileHandle, trackId: int, propName: str, value: float
) -> None: ...
def MP4SetTrackStringProperty(
    hFile: MP4FileHandle, trackId: int, propName: str, value: str
) -> None: ...
def MP4SetTrackBytesProperty(
    hFile: MP4FileHandle, trackId: int, propName: str, pValue: bytes
) -> None: ...
def MP4ReadSample(hFile: MP4FileHandle, trackId: int, sampleId: int) -> MP4Sample: ...
def MP4ReadSampleFromTime(
    hFile: MP4FileHandle, trackId: int, when: int
) -> MP4Sample: ...
def MP4WriteSample(
    hFile: MP4FileHandle,
    trackId: int,
    pBytes: bytes,
    duration: int = ...,
    renderingOffset: int = 0,
    isSyncSample: bool = True,
) -> None: ...
def MP4CopySample(
    srcFile: MP4FileHandle,
    srcTrackId: int,
    srcSampleId: int,
    dstFile: Optional[MP4FileHandle] = None,
    dstTrackId: int = ...,
    dstSampleDuration: int = ...,
) -> None: ...
def MP4GetSampleSize(hFile: MP4FileHandle, trackId: int, sampleId: int) -> int: ...
def MP4GetSampleIdFromTime(
    hFile: MP4FileHandle, trackId: int, when: int, wantSyncSample: bool = False
) -> int: ...
def MP4GetSampleTime(hFile: MP4FileHandle, trackId: int, sampleId: int) -> int: ...
def MP4GetSampleDuration(hFile: MP4FileHandle, trackId: int, sampleId: int) -> int: ...
def MP4GetSampleSync(hFile: MP4FileHandle, trackId: int, sampleId: int) -> bool: ...
def MP4GetTrackNumberOfSamples(hFile: MP4FileHandle, trackId: int) -> int: ...
def MP4GetTrackMaxSampleSize(hFile: MP4FileHandle, trackId: int) -> int: ...
def MP4TagsAlloc() -> MP4Tags: ...
def MP4TagsFree(tags: MP4Tags) -> None: ...
def MP4TagsFetch(tags: MP4Tags, hFile: MP4FileHandle) -> None: ...
def MP4TagsStore(tags: MP4Tags, hFile: MP4FileHandle) -> None: ...
def MP4TagsHasMetadata(tags: MP4Tags) -> bool: ...
def MP4TagsAddArtwork(
    tags: MP4Tags, data: bytes, type: MP4TagArtworkType_e = ...
) -> None: ...
def MP4TagsSetArtwork(
    tags: MP4Tags, index: int, data: bytes, type: MP4TagArtworkType_e = ...
) -> None: ...
def MP4TagsRemoveArtwork(tags: MP4Tags, index: int) -> None: ...
def MP4TagsSetName(tags: MP4Tags, value: Optional[str] = None) -> None: ...
def MP4TagsSetArtist(tags: MP4Tags, value: Optional[str] = None) -> None: ...
def MP4TagsSetAlbumArtist(tags: MP4Tags, value: Optional[str] = None) -> None: ...
def MP4TagsSetAlbum(tags: MP4Tags, value: Optional[str] = None) -> None: ...
def MP4TagsSetGrouping(tags: MP4Tags, value: Optional[str] = None) -> None: ...
def MP4TagsSetComposer(tags: MP4Tags, value: Optional[str] = None) -> None: ...
def MP4TagsSetComments(tags: MP4Tags, value: Optional[str] = None) -> None: ...
def MP4TagsSetGenre(tags: MP4Tags, value: Optional[str] = None) -> None: ...
def MP4TagsSetReleaseDate(tags: MP4Tags, value: Optional[str] = None) -> None: ...
def MP4TagsSetTVShow(tags: MP4Tags, value: Optional[str] = None) -> None: ...
def MP4TagsSetTVNetwork(tags: MP4Tags, value: Optional[str] = None) -> None: ...
def MP4TagsSetTVEpisodeID(tags: MP4Tags, value: Optional[str] = None) -> None: ...
def MP4TagsSetDescription(tags: MP4Tags, value: Optional[str] = None) -> None: ...
def MP4TagsSetLongDescription(tags: MP4Tags, value: Optional[str] = None) -> None: ...
def MP4TagsSetLyrics(tags: MP4Tags, value: Optional[str] = None) -> None: ...
def MP4TagsSetSortName(tags: MP4Tags, value: Optional[str] = None) -> None: ...
def MP4TagsSetSortArtist(tags: MP4Tags, value: Optional[str] = None) -> None: ...
def MP4TagsSetSortAlbumArtist(tags: MP4Tags, value: Optional[str] = None) -> None: ...
def MP4TagsSetSortAlbum(tags: MP4Tags, value: Optional[str] = None) -> None: ...
def MP4TagsSetSortComposer(tags: MP4Tags, value: Optional[str] = None) -> None: ...
def MP4TagsSetSortTVShow(tags: MP4Tags, value: Optional[str] = None) -> None: ...
def MP4TagsSetCopyright(tags: MP4Tags, value: Optional[str] = None) -> None: ...
def MP4TagsSetEncodingTool(tags: MP4Tags, value: Optional[str] = None) -> None: ...
def MP4TagsSetEncodedBy(tags: MP4Tags, value: Optional[str] = None) -> None: ...
def MP4TagsSetPurchaseDate(tags: MP4Tags, value: Optional[str] = None) -> None: ...
def MP4TagsSetKeywords(tags: MP4Tags, value: Optional[str] = None) -> None: ...
def MP4TagsSetCategory(tags: MP4Tags, value: Optional[str] = None) -> None: ...
def MP4TagsSetITunesAccount(tags: MP4Tags, value: Optional[str] = None) -> None: ...
def MP4TagsSetXID(tags: MP4Tags, value: Optional[str] = None) -> None: ...
def MP4TagsSetGenreType(tags: MP4Tags, value: Optional[int] = None) -> None: ...
def MP4TagsSetCompilation(tags: MP4Tags, value: Optional[int] = None) -> None: ...
def MP4TagsSetTVSeason(tags: MP4Tags, value: Optional[int] = None) -> None: ...
def MP4TagsSetTVEpisode(tags: MP4Tags, value: Optional[int] = None) -> None: ...
def MP4TagsSetPodcast(tags: MP4Tags, value: Optional[int] = None) -> None: ...
def MP4TagsSetHDVideo(tags: MP4Tags, value: Optional[int] = None) -> None: ...
def MP4TagsSetMediaType(tags: MP4Tags, value: Optional[int] = None) -> None: ...
def MP4TagsSetContentRating(tags: MP4Tags, value: Optional[int] = None) -> None: ...
def MP4TagsSetGapless(tags: MP4Tags, value: Optional[int] = None) -> None: ...
def MP4TagsSetITunesAccountType(tags: MP4Tags, value: Optional[int] = None) -> None: ...
def MP4TagsSetITunesCountry(tags: MP4Tags, value: Optional[int] = None) -> None: ...
def MP4TagsSetContentID(tags: MP4Tags, value: Optional[int] = None) -> None: ...
def MP4TagsSetArtistID(tags: MP4Tags, value: Optional[int] = None) -> None: ...
def MP4TagsSetPlaylistID(tags: MP4Tags, value: Optional[int] = None) -> None: ...
def MP4TagsSetGenreID(tags: MP4Tags, value: Optional[int] = None) -> None: ...
def MP4TagsSetComposerID(tags: MP4Tags, value: Optional[int] = None) -> None: ...
def MP4TagsSetTrack(tags: MP4Tags, value: Optional[MP4TagTrack] = None) -> None: ...
def MP4TagsSetDisk(tags: MP4Tags, value: Optional[MP4TagDisk] = None) -> None: ...
def MP4TagsSetTempo(tags: MP4Tags, value: Optional[int] = None) -> None: ...
def MP4AddChapterTextTrack(
    hFile: MP4FileHandle, refTrackId: int, timescale: int = 0
) -> int: ...
def MP4AddChapter(
    hFile: MP4FileHandle,
    chapterTrackId: int,
    chapterDuration: int,
    chapterTitle: Optional[str] = None,
) -> None: ...
def MP4AddNeroChapter(
    hFile: MP4FileHandle, chapterStart: int, chapterTitle: Optional[str] = None
) -> None: ...
def MP4ConvertChapters(
    hFile: MP4FileHandle, toChapterType: MP4ChapterType = ...
) -> MP4ChapterType: ...
def MP4DeleteChapters(
    hFile: MP4FileHandle,
    chapterType: MP4ChapterType = ...,
    chapterTrackId: int = ...,
) -> MP4ChapterType: ...
def MP4GetChapters(
    hFile: MP4FileHandle, chapterType: MP4ChapterType = ...
) -> MP4ChapterList: ...
def MP4SetChapters(
    hFile: MP4FileHandle,
    chapterList: Sequence[MP4Chapter],
    chapterType: MP4ChapterType = ...,
) -> MP4ChapterType: ...
